---
collections:
  - name: ansible.controller
    version: ">=4.5.0,<4.6.0"

  - name: infra.controller_configuration
    version: "2.5.1"

  - name: ansible.windows
  - name: community.windows
  - name: community.general
