---
all:
  children:

    linux_nodes:
      hosts:
        linux01:
          ansible_host: 35.170.79.71   # linux-node1
        linux02:
          ansible_host: 3.234.227.127  # linux-node2

    windows_nodes:
      vars:
        ansible_connection: winrm
        ansible_port: 5985
        ansible_winrm_scheme: http
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
      hosts:
        win01:
          ansible_host: 44.203.217.63  # windows-node-base    
