---
all:
  children:

    linux_nodes:
      hosts:
        linux01:
          ansible_host: 3.208.90.124   # linux-node1
        linux02:
          ansible_host: 34.237.220.162  # linux-node2

    windows_nodes:
      vars:
        ansible_connection: winrm
        ansible_port: 5985
        ansible_winrm_scheme: http
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
      hosts:
        win01:
          ansible_host: 3.89.80.249  # windows-node-base    
